# A demonstration of the autonomous decision making system

### The intent of this notebook is to demonstrate the use of a decision making system for the Nova Rover. In order to do this we need to: 
1. Simulate the rover's motion and detections in a simulated environment.
2. Simulate detected obstacles and targets
3. Demonstrate decision making system that avoids 

In [4]:
import numpy as np
class rover:
    def __init__(self):
        # Initial conditions selected arbitrarily
        self.x = 0
        self.y = 0 
        self.theta = 0
        self.world = np.zeros((100,100))
    def moveToPosition(self,new_x,new_y):
        self.x = new_x
        self.y = new_y
    

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
